import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";

import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Has Quiz App",
  description: "Generated by Hasanali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          
          <link rel="icon" href="./favicon.png" />
        </head>
        <body className="bg-black">
          {children}
          <Toaster richColors />
        </body>
      </html>
    </ClerkProvider>
  );
}
